/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAbsensi.java
 *
 * Created on 10 Des 12, 20:42:02
 */

package form.gaji;

import entity.Absensi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sql.methodes.SqlAbsensi;
import sql.methodes.SqlPegawai;
import table.TblAbsensi;
import tablechoice.TblChPegawai;
import tools.AutoFitTableColumns;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class frmAbsensi extends Form {

    private boolean isEdit = false;
    private int noJam,jph;
   // private String jph;
    private double  jam,mnt,ttljm,jth;
    /** Creates new form frmAbsensi */
    public frmAbsensi() {
        initComponents();        
        isiCombo();
        statusAwal();
        jamAwal();
        tampilData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPaanelInt1 = new tools.MyPaanelInt();
        jPanel1 = new javax.swing.JPanel();
        pnlId = new javax.swing.JPanel();
        txIdAbs = new javax.swing.JTextField();
        txIdPeg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tx8Jam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tx6Hr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btHtg = new javax.swing.JButton();
        pnlJam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblNmr = new javax.swing.JLabel();
        txJam = new javax.swing.JTextField();
        txMnt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btTmbh = new javax.swing.JButton();
        btUlg = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbDt = new javax.swing.JLabel();
        cbbBln = new javax.swing.JComboBox();
        cbbThn = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tx25Hr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnlPeg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeg = new javax.swing.JTable();
        txNmPeg = new javax.swing.JTextField();
        btCrPeg = new javax.swing.JButton();
        btSimpan = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAbs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_RIGHT);
        setAnimationShow(usu.widget.constan.Animation.SHOW_FROM_LEFT);
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Data Absensi ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);

        txIdAbs.setText("jTextField1");

        txIdPeg.setText("jTextField2");

        javax.swing.GroupLayout pnlIdLayout = new javax.swing.GroupLayout(pnlId);
        pnlId.setLayout(pnlIdLayout);
        pnlIdLayout.setHorizontalGroup(
            pnlIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdLayout.createSequentialGroup()
                .addComponent(txIdAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txIdPeg, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );
        pnlIdLayout.setVerticalGroup(
            pnlIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txIdAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Nama Pegawai");

        jLabel2.setText("Bulan");

        jLabel3.setText("Tahun");

        jLabel6.setText("Jam Kerja perHari");

        tx8Jam.setText("jTextField7");

        jLabel7.setText("jam");

        jLabel8.setText("Jumlah Hari Hadir");

        tx6Hr.setText("jTextField8");

        jLabel9.setText("hari");

        btHtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hit.png"))); // NOI18N
        btHtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHtgActionPerformed(evt);
            }
        });

        pnlJam.setBorder(javax.swing.BorderFactory.createTitledBorder(" Masukkan Absensi perHari "));
        pnlJam.setOpaque(false);

        jLabel10.setText("Jam");

        lblNmr.setText("No");

        txJam.setText("jTextField9");

        txMnt.setText("jTextField10");

        jLabel12.setText("Menit");

        btTmbh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_add.png"))); // NOI18N
        btTmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTmbhActionPerformed(evt);
            }
        });

        btUlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btUlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUlgActionPerformed(evt);
            }
        });

        jLabel11.setText("Data");

        lbDt.setText("Data");

        javax.swing.GroupLayout pnlJamLayout = new javax.swing.GroupLayout(pnlJam);
        pnlJam.setLayout(pnlJamLayout);
        pnlJamLayout.setHorizontalGroup(
            pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNmr)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txJam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlJamLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pnlJamLayout.createSequentialGroup()
                        .addComponent(txMnt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTmbh, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUlg, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlJamLayout.setVerticalGroup(
            pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJamLayout.createSequentialGroup()
                .addGroup(pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(lbDt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btUlg)
                    .addGroup(pnlJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txMnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btTmbh)
                        .addComponent(lblNmr)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbbBln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        cbbThn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbThn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThnActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah Hari Kerja");

        tx25Hr.setText("jTextField1");

        jLabel5.setText("hari");

        pnlPeg.setOpaque(false);

        tblPeg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblPeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPegMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeg);

        javax.swing.GroupLayout pnlPegLayout = new javax.swing.GroupLayout(pnlPeg);
        pnlPeg.setLayout(pnlPegLayout);
        pnlPegLayout.setHorizontalGroup(
            pnlPegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlPegLayout.setVerticalGroup(
            pnlPegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        txNmPeg.setText("Albertus Dimaswara");
        txNmPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNmPegActionPerformed(evt);
            }
        });

        btCrPeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.png"))); // NOI18N
        btCrPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrPegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txNmPeg, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCrPeg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbThn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbBln, 0, 174, Short.MAX_VALUE)))
                            .addComponent(pnlPeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tx25Hr, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                            .addComponent(tx8Jam))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tx6Hr, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btHtg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(pnlJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tx25Hr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tx8Jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btHtg)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btCrPeg)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tx6Hr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(18, 18, 18)
                        .addComponent(pnlJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txNmPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okeLgn.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_edit.png"))); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelLgn.png"))); // NOI18N
        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btTutup.setText("Tutup");
        btTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTutupActionPerformed(evt);
            }
        });

        tblAbs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblAbs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAbsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAbs);

        javax.swing.GroupLayout myPaanelInt1Layout = new javax.swing.GroupLayout(myPaanelInt1);
        myPaanelInt1.setLayout(myPaanelInt1Layout);
        myPaanelInt1Layout.setHorizontalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(myPaanelInt1Layout.createSequentialGroup()
                        .addComponent(btSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btTutup)))
                .addContainerGap())
        );
        myPaanelInt1Layout.setVerticalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btEdit)
                    .addComponent(btHapus)
                    .addComponent(btTutup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(myPaanelInt1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-598)/2, (screenSize.height-484)/2, 598, 484);
    }// </editor-fold>//GEN-END:initComponents

    private void isiCombo(){
        cbbThn.removeAllItems();
        int th = 2010;
        for(int i=0;i<11;i++){
            cbbThn.addItem(th);
            th ++;
        }
    }

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tambah")){
            siapSimpan();
            kosongJText();
            btCrPeg.requestFocus();
            isEdit = false;
        }else{
            if(txIdPeg.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Pegawai harus dipilih!", "Peringatan", JOptionPane.OK_OPTION);
                btCrPeg.requestFocus();
                return;
            }
            if(tx25Hr.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Jumlah Hari Kerja harus diisi!", "Peringatan", JOptionPane.OK_OPTION);
                tx25Hr.requestFocus();
                return;
            } else {
                try {
                    int t25kr = Integer.parseInt(tx25Hr.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Jumlah Hari Kerja harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                    tx25Hr.requestFocus();
                    return;
                }
            }
            if(tx6Hr.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Jumlah Hari Hadir harus diisi!", "Peringatan", JOptionPane.OK_OPTION);
                btHtg.requestFocus();
                return;
            }
            
            Absensi abs = new Absensi();
            abs.setIdPeg(Integer.parseInt(txIdPeg.getText()));
            abs.setJmHrKj(Integer.parseInt(tx25Hr.getText()));
            abs.setjKrHr(Integer.parseInt(tx8Jam.getText()));
            abs.setjHrHd(Integer.parseInt(tx6Hr.getText()));
            abs.setBln((String) cbbBln.getSelectedItem());
            abs.setThn(Integer.parseInt(cbbThn.getSelectedItem().toString()));

            SqlAbsensi qab = new SqlAbsensi(KonekDB.getKonek());
            if(isEdit){                    
                if(jph != abs.getjKrHr()){
                    JOptionPane.showMessageDialog(this, "Masukkan ulang jumlah hari hadir!", "Peringatan", JOptionPane.OK_OPTION);
                    //pnlJam.setVisible(true);
                    btHtg.requestFocus();
                    return;
                }else{
                    abs.setIdAbs(Integer.parseInt(txIdAbs.getText()));
                    qab.update(abs, Integer.parseInt(txIdAbs.getText()));
                }
            }else{
                qab.insert(abs);
            }

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
            tampilData();
            statusAwal();         
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        isEdit = true;
        siapSimpan();
    }//GEN-LAST:event_btEditActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        if (tblAbs.getSelectedRow() >= 0 && JOptionPane.showConfirmDialog(this, "Data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == 0){
            SqlAbsensi qab = new SqlAbsensi(KonekDB.getKonek());
            qab.delete(Integer.parseInt(txIdAbs.getText()));

            tampilData();
            JOptionPane.showMessageDialog(this, "Data telah dihapus.");
            statusAwal();
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tutup")){
            this.setVisible(false);
        }else{
            statusAwal();
        }
    }//GEN-LAST:event_btTutupActionPerformed

    private void tblAbsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAbsMouseClicked
        // TODO add your handling code here:
        tabelKlik();        
        txIdAbs.setText(tblAbs.getValueAt(tblAbs.getSelectedRow(),0).toString());        
        txNmPeg.setText(tblAbs.getValueAt(tblAbs.getSelectedRow(),1).toString());
        cbbBln.setSelectedItem(tblAbs.getValueAt(tblAbs.getSelectedRow(),2));
        cbbThn.setSelectedItem(tblAbs.getValueAt(tblAbs.getSelectedRow(),3));
        tx25Hr.setText(tblAbs.getValueAt(tblAbs.getSelectedRow(),4).toString());
        tx8Jam.setText(tblAbs.getValueAt(tblAbs.getSelectedRow(),5).toString());
        tx6Hr.setText(tblAbs.getValueAt(tblAbs.getSelectedRow(),6).toString());
        
        /*-------------------------------------------------------------------*/
        int idAbs =Integer.parseInt(txIdAbs.getText()) ;
        String sql = "SELECT * FROM tbl_absensi WHERE idAbsen='"+idAbs+"'";
        try {
            Connection conn = KonekDB.getKonek();
            Statement sm = conn.createStatement();
            ResultSet rs = sm.executeQuery(sql);
            if(rs.next()){
                txIdPeg.setText(Integer.toString(rs.getInt("idPegawai")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAbsensi.class.getName()).log(Level.SEVERE, null, ex);
        }
        jph = Integer.parseInt(tx8Jam.getText()) ;   //Untuk keperluan syarat edit jam kerja/hari
    }//GEN-LAST:event_tblAbsMouseClicked

    private void btCrPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrPegActionPerformed
        // TODO add your handling code here:
        pnlPeg.setVisible(true);
        SqlPegawai qpg = new SqlPegawai(KonekDB.getKonek());
        tblPeg.setModel(new TblChPegawai(qpg.getAll()));
        AutoFitTableColumns.autoResizeTable(tblPeg, true);
    }//GEN-LAST:event_btCrPegActionPerformed

    private void tblPegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegMouseClicked
        // TODO add your handling code here:
        txIdPeg.setText(tblPeg.getValueAt(tblPeg.getSelectedRow(),0).toString());
        txNmPeg.setText(tblPeg.getValueAt(tblPeg .getSelectedRow(),2).toString());
    }//GEN-LAST:event_tblPegMouseClicked

    private void btHtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHtgActionPerformed
        // TODO add your handling code here:
        pnlJam.setVisible(true);
        jamAwal();
    }//GEN-LAST:event_btHtgActionPerformed

    private void btTmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTmbhActionPerformed
        // TODO add your handling code here:
        double jk, jm, mt;
        if(tx8Jam.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Jam Kerja perHari harus diisi!", "Peringatan", JOptionPane.OK_OPTION);
            tx8Jam.requestFocus();
            return;
        } else {
            try {
                jk = Double.parseDouble(tx8Jam.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Jam Kerja perHari harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                tx8Jam.requestFocus();
                return;
            }
        }
        if(txJam.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Jam harus diisi!", "Peringatan", JOptionPane.OK_OPTION);
            txJam.requestFocus();
            return;
        } else {
            try {
                jm = Double.parseDouble(txJam.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Jam harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                txJam.requestFocus();
                return;
            }
        }
        if(txMnt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Menit harus diisi!", "Peringatan", JOptionPane.OK_OPTION);
            txMnt.requestFocus();
            return;
        } else {
            try {
                mt = Double.parseDouble(txMnt.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Menit harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                txMnt.requestFocus();
                return;
            }
        }
        
        /***** Memberi nomor masukan ******/
        lbDt.setText("1");
        int no = Integer.parseInt(lbDt.getText()) ;
        noJam = noJam+no;
        lblNmr.setText(Integer.toString(noJam));

        /***** Menjumlahkan Jam masukkan ******/
        //double jm = Double.parseDouble(txJam.getText()) ;
        jam = jam+jm;

        /***** Menjumlahkan menit masukan ******/
        //double mt = Double.parseDouble(txMnt.getText()) ;
        mnt = mnt+mt;

        /***** Menambahkan menit kedalam jam ******/
        ttljm = jam + Math.ceil(mnt/60);

        /***** Total jam hadir di konvert ke Hari ******/
       // double jk = Double.parseDouble(tx8Jam.getText());
        jth = Math.ceil(ttljm/jk);

        DecimalFormat df = new DecimalFormat("#");
        tx6Hr.setText(df.format(jth));
        txJam.setText("");           
        txMnt.setText("");
        txJam.requestFocus();

        jph = Integer.parseInt(tx8Jam.getText()); //Untuk keperluan syarat edit jam kerja/hari
    }//GEN-LAST:event_btTmbhActionPerformed

    private void btUlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUlgActionPerformed
        // TODO add your handling code here:
        jamAwal();
    }//GEN-LAST:event_btUlgActionPerformed

    private void txNmPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNmPegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNmPegActionPerformed

    private void cbbThnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrPeg;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btHtg;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTmbh;
    private javax.swing.JButton btTutup;
    private javax.swing.JButton btUlg;
    private javax.swing.JComboBox cbbBln;
    private javax.swing.JComboBox cbbThn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDt;
    private javax.swing.JLabel lblNmr;
    private tools.MyPaanelInt myPaanelInt1;
    private javax.swing.JPanel pnlId;
    private javax.swing.JPanel pnlJam;
    private javax.swing.JPanel pnlPeg;
    private javax.swing.JTable tblAbs;
    private javax.swing.JTable tblPeg;
    private javax.swing.JTextField tx25Hr;
    private javax.swing.JTextField tx6Hr;
    private javax.swing.JTextField tx8Jam;
    private javax.swing.JTextField txIdAbs;
    private javax.swing.JTextField txIdPeg;
    private javax.swing.JTextField txJam;
    private javax.swing.JTextField txMnt;
    private javax.swing.JTextField txNmPeg;
    // End of variables declaration//GEN-END:variables

    private void statusAwal(){
        kosongJText();
        setInputan(false);
        btSimpan.setText("Tambah");
        btEdit.setText("Edit");
        btHapus.setText("Hapus");
        btTutup.setText("Tutup");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
        pnlId.setVisible(false);
        pnlPeg.setVisible(false);
        pnlJam.setVisible(false);
        lbDt.setVisible(false);
    }

    private void siapSimpan(){
        setInputan(true);
        btSimpan.setText("Simpan");
        btTutup.setText("Batal");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
    }

    private void tabelKlik(){
        setInputan(false);
        btSimpan.setEnabled(false);
        btEdit.setEnabled(true);
        btHapus.setEnabled(true);
        btTutup.setText("Batal");        
    }

    private void kosongJText(){
        txIdAbs.setText("");
        txIdPeg.setText("");
        txNmPeg.setText("");
        cbbBln.setSelectedIndex(0);
        cbbThn.setSelectedIndex(3);
        tx25Hr.setText("");
        tx8Jam.setText("");
        tx6Hr.setText("");
    }

    private void setInputan(boolean aktif){
        txNmPeg.setEnabled(false);
        tx6Hr.setEnabled(false);        
        cbbBln.setEnabled(aktif);
        cbbThn.setEnabled(aktif);
        tx25Hr.setEnabled(aktif);
        tx8Jam.setEnabled(aktif);        
        btCrPeg.setEnabled(aktif);
        btHtg.setEnabled(aktif);
    }
    
    private void jamAwal(){
        noJam = 0;
        jam = 0;
        mnt = 0;
        ttljm = 0;
        jth = 0;
        noJam = noJam+1;
        lblNmr.setText(Integer.toString(noJam));
        txJam.setText("");
        txMnt.setText("");
        tx6Hr.setText("");
    }
    private void tampilData(){
        SqlAbsensi qab = new SqlAbsensi(KonekDB.getKonek());
        tblAbs.setModel(new TblAbsensi(qab.getAll()));
        AutoFitTableColumns.autoResizeTable(tblAbs, true);
    }
}
