/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmLaporan.java
 *
 * Created on 18 Des 12, 8:29:25
 */

package form.gaji;

import form.report.reportRekapAll;
import form.report.reportSlipAll;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class frmLaporan extends Form {

    /** Creates new form frmLaporan */
    public frmLaporan() {
        initComponents();
        awal();
        isiCombo();
    }
    
    

    private void isiCombo(){
        cbTahun.removeAllItems();
        int th = 2010;
        for(int i=0;i<11;i++){
            cbTahun.addItem(th);
            th ++;
        }
        cbTahun.setSelectedItem(2013);

        cbSlp.removeAllItems();
        String sql = "SELECT noSlip FROM gaji_rekap";
        Connection conn = KonekDB.getKonek();
        Statement sm;
        try {
            sm = conn.createStatement();
            ResultSet rs = sm.executeQuery(sql);
            while(rs.next()){
                cbSlp.addItem(rs.getString("noSlip"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGr = new javax.swing.ButtonGroup();
        myPaanelInt1 = new tools.MyPaanelInt();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbRkp = new javax.swing.JRadioButton();
        rbSlpA = new javax.swing.JRadioButton();
        rbSlpO = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbBln = new javax.swing.JComboBox();
        cbTahun = new javax.swing.JComboBox();
        cbSlp = new javax.swing.JComboBox();
        btCtk = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_RIGHT);
        setAnimationShow(usu.widget.constan.Animation.SHOW_FROM_LEFT);
        setResizable(false);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Cetak Laporan Penggajian ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Laporan"));
        jPanel3.setOpaque(false);

        rdGr.add(rbRkp);
        rbRkp.setText("Rekapitulasi Data Penggajian");
        rbRkp.setOpaque(false);
        rbRkp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRkpMouseClicked(evt);
            }
        });

        rdGr.add(rbSlpA);
        rbSlpA.setText("Slip Penggajian seluruh Karyawan");
        rbSlpA.setOpaque(false);
        rbSlpA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSlpAMouseClicked(evt);
            }
        });

        rdGr.add(rbSlpO);
        rbSlpO.setText("Slip Penggajian satu Karyawan");
        rbSlpO.setOpaque(false);
        rbSlpO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSlpOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbRkp)
                    .addComponent(rbSlpA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSlpO))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbRkp)
                .addGap(18, 18, 18)
                .addComponent(rbSlpA)
                .addGap(18, 18, 18)
                .addComponent(rbSlpO)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(" Parameter "));
        jPanel4.setOpaque(false);

        jLabel1.setText("Bulan");

        jLabel2.setText("Tahun");

        jLabel3.setText("No. Slip");

        cbBln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbSlp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTahun, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(cbSlp, 0, 0, Short.MAX_VALUE)
                    .addComponent(cbBln, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btCtk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btCtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrLaporan.png"))); // NOI18N
        btCtk.setText("   Laporan");
        btCtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCtkActionPerformed(evt);
            }
        });

        btTutup.setFont(new java.awt.Font("Times New Roman", 1, 12));
        btTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btTutup.setText("Tutup");
        btTutup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTutup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btCtk, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTutup))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btTutup, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btCtk, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout myPaanelInt1Layout = new javax.swing.GroupLayout(myPaanelInt1);
        myPaanelInt1.setLayout(myPaanelInt1Layout);
        myPaanelInt1Layout.setHorizontalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        myPaanelInt1Layout.setVerticalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(myPaanelInt1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-536)/2, (screenSize.height-267)/2, 536, 267);
    }// </editor-fold>//GEN-END:initComponents

    private void btCtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCtkActionPerformed
        // TODO add your handling code here:
        if(rbRkp.isSelected()){
            String bln = (String) cbBln.getSelectedItem();
            int thn = Integer.parseInt(cbTahun.getSelectedItem().toString());

            reportRekapAll rra = new reportRekapAll(bln, thn);           
            rra.setVisible(true);
        }else if(rbSlpA.isSelected()){
            String bln = (String) cbBln.getSelectedItem();
            int thn = Integer.parseInt(cbTahun.getSelectedItem().toString());

            reportSlipAll rsa = new reportSlipAll(bln, thn, "");
            rsa.setVisible(true);
        }else{
            String slp = (String) cbSlp.getSelectedItem();

            reportSlipAll rsa = new reportSlipAll("", 0, slp);
            rsa.setVisible(true);
        }
    }//GEN-LAST:event_btCtkActionPerformed

    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btTutupActionPerformed

    private void rbRkpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRkpMouseClicked
        // TODO add your handling code here:
        cont(true);
    }//GEN-LAST:event_rbRkpMouseClicked

    private void rbSlpAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSlpAMouseClicked
        // TODO add your handling code here:
        cont(true);
    }//GEN-LAST:event_rbSlpAMouseClicked

    private void rbSlpOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSlpOMouseClicked
        // TODO add your handling code here:
        cont(false);
    }//GEN-LAST:event_rbSlpOMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCtk;
    private javax.swing.JButton btTutup;
    private javax.swing.JComboBox cbBln;
    private javax.swing.JComboBox cbSlp;
    private javax.swing.JComboBox cbTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private tools.MyPaanelInt myPaanelInt1;
    private javax.swing.JRadioButton rbRkp;
    private javax.swing.JRadioButton rbSlpA;
    private javax.swing.JRadioButton rbSlpO;
    private javax.swing.ButtonGroup rdGr;
    // End of variables declaration//GEN-END:variables

    private void awal(){
        rbRkp.setSelected(true);
        cont(true);
    }

    private void cont(boolean a){
        cbBln.setEnabled(a);
        cbTahun.setEnabled(a);
        cbSlp.setEnabled(!a);
    }
}
