/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPotongan.java
 *
 * Created on 07 Des 12, 16:26:01
 */

package form.gaji;

import entity.Potongan;
import javax.swing.JOptionPane;
import sql.methodes.SqlPotongan;
import table.TblPotongan;
import tools.AutoFitTableColumns;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class frmPotongan extends Form {

    private boolean isEdit = false;
    /** Creates new form frmPotongan */
    public frmPotongan() {
        initComponents();
        statusAwal();
        tampilData();
      //this.setIconImage(new ImageIcon(getClass().getResource("/images/mnPotong.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPaanelInt1 = new tools.MyPaanelInt();
        btSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPotong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNmPot = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        btEdit = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Form Potongan");
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_RIGHT);
        setAnimationShow(usu.widget.constan.Animation.SHOW_FROM_LEFT);
        setResizable(false);
        setUndecorated(true);

        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okeLgn.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        tblPotong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPotong.setOpaque(false);
        tblPotong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPotongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPotong);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Data Potongan ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setText("Nama Potongan");

        lbId.setText("ID Potongan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNmPot, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txNmPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_edit.png"))); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelLgn.png"))); // NOI18N
        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btTutup.setText("Tutup");
        btTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPaanelInt1Layout = new javax.swing.GroupLayout(myPaanelInt1);
        myPaanelInt1.setLayout(myPaanelInt1Layout);
        myPaanelInt1Layout.setHorizontalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPaanelInt1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(myPaanelInt1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btTutup))
                    .addGroup(myPaanelInt1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)))
                .addContainerGap())
        );
        myPaanelInt1Layout.setVerticalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btEdit)
                    .addComponent(btHapus)
                    .addComponent(btTutup))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(myPaanelInt1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(this);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-415)/2, (screenSize.height-258)/2, 415, 258);
    }// </editor-fold>//GEN-END:initComponents

    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tutup")){
            this.setVisible(false);
        }else{
            statusAwal();
        }
    }//GEN-LAST:event_btTutupActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tambah")){
            siapSimpan();
            kosongJText();
            txNmPot.requestFocus();
            isEdit = false;
        } else{
            if(txNmPot.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nama Potongan harus diisi.!", "Peringatan", JOptionPane.OK_OPTION);
                txNmPot.requestFocus();
                return;
            }

            Potongan ptg = new Potongan();            
            ptg.setNmPot(txNmPot.getText());

            SqlPotongan qpt = new SqlPotongan(KonekDB.getKonek());
            if(isEdit){
                ptg.setIdPot(Integer.parseInt(txId.getText()));
                qpt.update(ptg, Integer.parseInt(txId.getText()));
            }else{
                qpt.insert(ptg);
            }

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
            tampilData();
            statusAwal();
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
            isEdit = true;
            siapSimpan();
    }//GEN-LAST:event_btEditActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
            if (tblPotong.getSelectedRow() >= 0 && JOptionPane.showConfirmDialog(this, "Data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == 0){
                SqlPotongan qpt = new SqlPotongan(KonekDB.getKonek());
                qpt.delete(Integer.parseInt(txId.getText()));
                
                tampilData();
                JOptionPane.showMessageDialog(this, "Data telah dihapus.");                
                statusAwal();
            }
    }//GEN-LAST:event_btHapusActionPerformed

    private void tblPotongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPotongMouseClicked
        // TODO add your handling code here:
        tabelKlik();
        txId.setText(tblPotong.getValueAt(tblPotong.getSelectedRow(),0).toString());
        txNmPot.setText(tblPotong.getValueAt(tblPotong.getSelectedRow(),1).toString());
    }//GEN-LAST:event_tblPotongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbId;
    private tools.MyPaanelInt myPaanelInt1;
    private javax.swing.JTable tblPotong;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txNmPot;
    // End of variables declaration//GEN-END:variables

    private void statusAwal(){
        kosongJText();
        setInputan(false);
        btSimpan.setText("Tambah");
        btEdit.setText("Edit");
        btHapus.setText("Hapus");
        btTutup.setText("Tutup");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
        lbId.setVisible(false);
        txId.setVisible(false);
    }
    
    private void siapSimpan(){
        setInputan(true);
        btSimpan.setText("Simpan");
        btTutup.setText("Batal");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
    }

    private void tabelKlik(){
        setInputan(false);
        btSimpan.setEnabled(false);
        btEdit.setEnabled(true);
        btHapus.setEnabled(true);
        btTutup.setText("Batal");
    }

    private void kosongJText(){
        txId.setText("");
        txNmPot.setText("");
    }    

    private void setInputan(boolean aktif){
        txNmPot.setEnabled(aktif);
    }

    private void tampilData(){
        SqlPotongan qpt = new SqlPotongan(KonekDB.getKonek());
        tblPotong.setModel(new TblPotongan(qpt.getAll()));
        AutoFitTableColumns.autoResizeTable(tblPotong, true);
    }
}
