/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPenggajian.java
 *
 * Created on 12 Des 12, 1:30:03
 */

package form.gaji;

import entity.DetPotongan;
import entity.Penggajian;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sql.methodes.SqlAbsensi;
import sql.methodes.SqlDetPotongan;
import sql.methodes.SqlPenggajian;
import sql.methodes.SqlPotongan;
import table.TblDetPotongan;
import table.TblPenggajian;
import table.TblPotongan;
import tablechoice.TblChAbsPegJab;
import tools.AutoFitTableColumns;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class frmPenggajian extends Form {

    private boolean isInAbs;
    private boolean isEdit = false;
    private boolean isEdpt = false;
    DecimalFormat df = new DecimalFormat("#");
    private double gj,gjk,tpot,gjb,tmp,gp,hk,hh;
    /** Creates new form frmPenggajian */
    public frmPenggajian(int ida) {
        initComponents();
        statusAwal();                
        nmUser(ida);
        tampilData();
        tpot = 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPaanelInt1 = new tools.MyPaanelInt();
        jPanel1 = new javax.swing.JPanel();
        pnlId = new javax.swing.JPanel();
        txIdGji = new javax.swing.JTextField();
        txIdAbs = new javax.swing.JTextField();
        txIdDP = new javax.swing.JTextField();
        txIdPot = new javax.swing.JTextField();
        txIdUsr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txSlip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txNmPeg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNmJab = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txHrKrj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txHrHdr = new javax.swing.JTextField();
        txAwGji = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txBln = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txThn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txInstf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txBns = new javax.swing.JTextField();
        txKtGji = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btKtGji = new javax.swing.JButton();
        btCrAbs = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlInp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInp = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txJmPot = new javax.swing.JTextField();
        btDlPot = new javax.swing.JButton();
        btEdPot = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPot = new javax.swing.JTable();
        txNmPot = new javax.swing.JTextField();
        txTtPot = new javax.swing.JTextField();
        btCrPot = new javax.swing.JButton();
        btSpPot = new javax.swing.JButton();
        btTtPot = new javax.swing.JButton();
        lblBsGji = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUsr = new javax.swing.JLabel();
        txGaPok = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGaji = new javax.swing.JTable();
        btCari = new javax.swing.JButton();
        txCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_RIGHT);
        setAnimationShow(usu.widget.constan.Animation.SHOW_FROM_LEFT);
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Proses Hitung Gaji ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setOpaque(false);

        txIdGji.setText("idgaji");

        txIdAbs.setText("idAbsen");

        txIdDP.setText("idDetPot");

        txIdPot.setText("idPot");

        txIdUsr.setText("idUsr");

        javax.swing.GroupLayout pnlIdLayout = new javax.swing.GroupLayout(pnlId);
        pnlId.setLayout(pnlIdLayout);
        pnlIdLayout.setHorizontalGroup(
            pnlIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdLayout.createSequentialGroup()
                .addComponent(txIdGji, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txIdAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(txIdDP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txIdPot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txIdUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        pnlIdLayout.setVerticalGroup(
            pnlIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txIdGji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txIdAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txIdDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txIdPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txIdUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Nomor Slip Gaji");

        txSlip.setText("jTextField8");

        jLabel2.setText("Absensi Pegawai");

        txNmPeg.setText("jTextField8");

        jLabel3.setText("Jabatan");

        txNmJab.setText("jTextField9");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jumlah Gaji sesuai Hari Hadir"));
        jPanel3.setOpaque(false);

        jLabel5.setText("Jml Hari Kerja");

        txHrKrj.setText("jTextField11");

        jLabel6.setText("Jml Hari Hadir");

        txHrHdr.setText("jTextField12");

        txAwGji.setText("jTextField13");

        jLabel7.setText("Jumlah Gaji");

        jLabel15.setText("Bulan");

        txBln.setText("jTextField19");

        jLabel16.setText("Tahun");

        txThn.setText("jTextField20");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txBln, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txThn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51)
                        .addComponent(txHrKrj, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txAwGji, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txHrHdr, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txHrKrj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txHrHdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txAwGji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Jumlah Gaji Kotor"));
        jPanel4.setOpaque(false);

        jLabel8.setText("Insentif");

        txInstf.setText("jTextField14");

        jLabel9.setText("Bonus");

        txBns.setText("jTextField15");

        txKtGji.setText("jTextField16");

        jLabel10.setText("Gaji Kotor");

        btKtGji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_add.png"))); // NOI18N
        btKtGji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKtGjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(80, 80, 80)
                                .addComponent(txInstf, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(88, 88, 88)
                                .addComponent(txBns, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txKtGji, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btKtGji, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txInstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txBns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txKtGji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(btKtGji))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCrAbs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.png"))); // NOI18N
        btCrAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrAbsActionPerformed(evt);
            }
        });

        jLabel4.setText("Gaji Pokok");

        tblInp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tabel Input"
            }
        ));
        tblInp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInp);

        javax.swing.GroupLayout pnlInpLayout = new javax.swing.GroupLayout(pnlInp);
        pnlInp.setLayout(pnlInpLayout);
        pnlInpLayout.setHorizontalGroup(
            pnlInpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        pnlInpLayout.setVerticalGroup(
            pnlInpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Potongan"));
        jPanel5.setOpaque(false);

        jLabel17.setText("Potongan");

        jLabel18.setText("Jumlah");

        txJmPot.setText("jTextField22");

        btDlPot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelT.png"))); // NOI18N
        btDlPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDlPotActionPerformed(evt);
            }
        });

        btEdPot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editT.png"))); // NOI18N
        btEdPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdPotActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Potongan");

        tblPot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tabel Potongan"
            }
        ));
        tblPot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPotMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPot);

        txNmPot.setText("jTextField1");

        txTtPot.setText("jTextField2");

        btCrPot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.png"))); // NOI18N
        btCrPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrPotActionPerformed(evt);
            }
        });

        btSpPot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okeT.png"))); // NOI18N
        btSpPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSpPotActionPerformed(evt);
            }
        });

        btTtPot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_add.png"))); // NOI18N
        btTtPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTtPotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txJmPot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txNmPot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btCrPot, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btEdPot, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btSpPot, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDlPot, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTtPot, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTtPot, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txNmPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCrPot)
                    .addComponent(btEdPot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDlPot)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSpPot)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txJmPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txTtPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(btTtPot))
                .addContainerGap())
        );

        lblBsGji.setFont(new java.awt.Font("Times New Roman", 1, 18));
        lblBsGji.setForeground(new java.awt.Color(255, 0, 51));
        lblBsGji.setText("0");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel12.setText("Gaji Bersih : Rp");

        lblUsr.setForeground(new java.awt.Color(0, 51, 255));
        lblUsr.setText("Herry Prasetya");

        txGaPok.setText("jTextField10");

        jLabel13.setText("Admin :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txGaPok)
                                    .addComponent(txNmJab)
                                    .addComponent(txSlip, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txNmPeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btCrAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlInp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBsGji, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txSlip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsr)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBsGji)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCrAbs)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txNmPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txNmJab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txGaPok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okeLgn.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_edit.png"))); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelLgn.png"))); // NOI18N
        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btTutup.setText("Tutup");
        btTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTutupActionPerformed(evt);
            }
        });

        tblGaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGajiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGaji);

        btCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        txCari.setForeground(new java.awt.Color(153, 153, 153));
        txCari.setText("Masukkan NO. SLIP disini.");
        txCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txCariMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout myPaanelInt1Layout = new javax.swing.GroupLayout(myPaanelInt1);
        myPaanelInt1.setLayout(myPaanelInt1Layout);
        myPaanelInt1Layout.setHorizontalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(myPaanelInt1Layout.createSequentialGroup()
                        .addComponent(btSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addComponent(btTutup)))
                .addContainerGap())
        );
        myPaanelInt1Layout.setVerticalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit)
                    .addComponent(btHapus)
                    .addComponent(btSimpan)
                    .addComponent(btCari)
                    .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTutup))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(myPaanelInt1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-926)/2, (screenSize.height-571)/2, 926, 571);
    }// </editor-fold>//GEN-END:initComponents
    
    private void otoId(){
        String sql = "SELECT MAX(idGaji) AS idGj FROM tbl_penggajian";
        try {
            Connection conn = KonekDB.getKonek();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){   
                String idg = Integer.toString(rs.getInt("idGj")+1);
                txIdGji.setText(idg);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MMM");
                Date dt = new Date();
                txSlip.setText("G/"+sdf.format(dt)+"/"+idg);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    

    private void nmUser(int ida){        
        String idAm = Integer.toString(ida);        
        txIdUsr.setText(idAm);        
        String sql = "SELECT nmPegawai FROM tbl_user AS u INNER JOIN tbl_pegawai AS p "
                + "ON p.idPegawai=u.idPegawai WHERE idUser='"+txIdUsr.getText()+"'";        
        try {
            Connection conn = KonekDB.getKonek();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                lblUsr.setText(rs.getString("nmPegawai"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tambah")){
            siapSimpan();
            otoId();
            tampilDataDetPot();
            btCrAbs.requestFocus();
            isEdit = false;
        }else{
            if(txNmPeg.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Absensi Pegawai harus dipilih!", "Peringatan", JOptionPane.OK_OPTION);
                btCrAbs.requestFocus();
                return;
            }
            if(lblBsGji.getText().equals("0")){
                JOptionPane.showMessageDialog(this, "Gaji Bersih harus dihitung terlebih dahulu!", "Peringatan", JOptionPane.OK_OPTION);
                btTtPot.requestFocus();
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dt = new Date();

            Penggajian pgj = new Penggajian();

            pgj.setIdGji(Integer.parseInt(txIdGji.getText()));
            pgj.setSlip(txSlip.getText());
            pgj.setIdAbs(Integer.parseInt(txIdAbs.getText()));
            pgj.setAwGji(Double.parseDouble(txAwGji.getText()));
            pgj.setInStf(Double.parseDouble(txInstf.getText()));
            pgj.setBns(Double.parseDouble(txBns.getText()));
            pgj.setKtGji(Double.parseDouble(txKtGji.getText()));
            pgj.setTtPot(Double.parseDouble(txTtPot.getText()));
            pgj.setBsGji(Double.parseDouble(lblBsGji.getText()));
           // pgj.setTgl(sdf.format(dt));
            pgj.setIdUsr(Integer.parseInt(txIdUsr.getText()));

            SqlPenggajian qgj = new SqlPenggajian(KonekDB.getKonek());
            if(isEdit){
                qgj.update(pgj, pgj.getIdGji());
            }else{
                qgj.insert(pgj);
            }

            tampilData();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
            statusAwal();
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        isEdit = true;
        siapSimpan();

        /*Hitung ulang scr auto gaji awal bila ada perubahan gapok/hari kerja/hari hadir*/
        gp = Double.parseDouble(txGaPok.getText());
        hk = Double.parseDouble(txHrKrj.getText());
        hh = Double.parseDouble(txHrHdr.getText());
        gj = gp/hk*hh;
        // DecimalFormat df = new DecimalFormat("#");
        txAwGji.setText(df.format(gj));
        /****************************/
        
        btCrAbs.setEnabled(true);
        tampilDataDetPot();
    }//GEN-LAST:event_btEditActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        if (tblGaji.getSelectedRow() >= 0 && JOptionPane.showConfirmDialog(this, "Data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == 0){
            SqlPenggajian qgj = new SqlPenggajian(KonekDB.getKonek());
            qgj.delete(Integer.parseInt(txIdAbs.getText()));

            tampilData();
            JOptionPane.showMessageDialog(this, "Data telah dihapus.");
            statusAwal();
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tutup")){
            this.setVisible(false);
        }else{
            gj=0;
            gjk=0;
            if(btSimpan.isEnabled()==true && isEdit==false){
                String sql = "SELECT * FROM tbl_detpotgaj WHERE idGaji='"+txIdGji.getText()+"'";
                Connection conn = KonekDB.getKonek();
                try {
                    Statement sm = conn.createStatement();
                    ResultSet rs = sm.executeQuery(sql);
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this,"Data Tabel Potongan harap dihapus!");
                        return;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            statusAwal();
        }
    }//GEN-LAST:event_btTutupActionPerformed

    private void tblGajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGajiMouseClicked
        // TODO add your handling code here:
        tabelKlik();
        txIdGji.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),0).toString());
        txSlip.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),1).toString());
        txNmPeg.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),2).toString());
        txNmJab.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),3).toString());
        txGaPok.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),4).toString());
        txBln.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),5).toString());
        txThn.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),6).toString());
        txHrKrj.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),7).toString());
        txHrHdr.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),8).toString());
        txAwGji.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),9).toString());
        txInstf.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),10).toString());
        txBns.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),11).toString());
        txKtGji.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),12).toString());
        txTtPot.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),13).toString());
        lblBsGji.setText(tblGaji.getValueAt(tblGaji.getSelectedRow(),14).toString());

        /****************************************************************/
        String idgj = txIdGji.getText();
        String sql = "SELECT * FROM tbl_penggajian WHERE idGaji='"+idgj+"'";
        Connection conn = KonekDB.getKonek();
        try {
            Statement sm = conn.createStatement();
            ResultSet rs = sm.executeQuery(sql);
            if(rs.next()){
                txIdAbs.setText(Integer.toString(rs.getInt("idAbsen")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
        }
        /****************************************************************/
        
        if(Integer.parseInt(txTtPot.getText())!=0){
            tblPot.setVisible(true);
            tampilDataDetPot();
    /*        SqlDetPotongan qdp = new SqlDetPotongan(KonekDB.getKonek());
            tblPot.setModel(new TblDetPotongan(qdp.getAll(Integer.parseInt(txIdGji.getText()))));
            AutoFitTableColumns.autoResizeTable(tblPot, true);
      */      tblPot.setEnabled(false);
        }
    }//GEN-LAST:event_tblGajiMouseClicked

    private void btCrAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrAbsActionPerformed
        // TODO add your handling code here:
        isInAbs = true;
        tblInp.setVisible(true);
        SqlAbsensi qas = new SqlAbsensi(KonekDB.getKonek());
        tblInp.setModel(new TblChAbsPegJab(qas.getAll()));
        AutoFitTableColumns.autoResizeTable(tblInp, true);
    }//GEN-LAST:event_btCrAbsActionPerformed

    private void tblInpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInpMouseClicked
        // TODO add your handling code here:
        if(isInAbs){
            txIdAbs.setText(tblInp.getValueAt(tblInp.getSelectedRow(),0).toString());
            txNmPeg.setText(tblInp.getValueAt(tblInp.getSelectedRow(),1).toString());
            txNmJab.setText(tblInp.getValueAt(tblInp.getSelectedRow(),2).toString());
            txGaPok.setText(tblInp.getValueAt(tblInp.getSelectedRow(),3).toString());
            txBln.setText(tblInp.getValueAt(tblInp.getSelectedRow(),4).toString());
            txThn.setText(tblInp.getValueAt(tblInp.getSelectedRow(),5).toString());
            txHrKrj.setText(tblInp.getValueAt(tblInp.getSelectedRow(),6).toString());
            txHrHdr.setText(tblInp.getValueAt(tblInp.getSelectedRow(),7).toString());

            gp = Double.parseDouble(txGaPok.getText());
            hk = Double.parseDouble(txHrKrj.getText());
            hh = Double.parseDouble(txHrHdr.getText());
            gj = gp/hk*hh;
           // DecimalFormat df = new DecimalFormat("#");
            txAwGji.setText(df.format(gj));
            txInstf.requestFocus();
        }else{       
            btSpPot.setEnabled(true);
            btEdPot.setEnabled(false);
            btDlPot.setEnabled(false);
            isEdpt = false;
            txIdPot.setText(tblInp.getValueAt(tblInp.getSelectedRow(),0).toString());
            txNmPot.setText(tblInp.getValueAt(tblInp.getSelectedRow(),1).toString());
            txJmPot.setEnabled(true);
            txJmPot.setText("");
            txJmPot.requestFocus();
        }
    }//GEN-LAST:event_tblInpMouseClicked

    private void btCrPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrPotActionPerformed
        // TODO add your handling code here:
        isInAbs = false;
        tblInp.setVisible(true);
        SqlPotongan qpt = new SqlPotongan(KonekDB.getKonek());
        tblInp.setModel(new TblPotongan(qpt.getAll()));
        AutoFitTableColumns.autoResizeTable(tblInp, true);
    }//GEN-LAST:event_btCrPotActionPerformed

    private void btSpPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSpPotActionPerformed
        // TODO add your handling code here:
        double jpot;
        if(txIdPot.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Potongan harus dipilih!", "Peringatan", JOptionPane.OK_OPTION);
            btCrPot.requestFocus();
            return;
        }
        if(txJmPot.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Jumlah Potongan harus diisi.!", "Peringatan", JOptionPane.OK_OPTION);
            txJmPot.requestFocus();
            return;
        } else {
            try {
                jpot = Double.parseDouble(txJmPot.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Jumlah Potongan harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                txJmPot.requestFocus();
                return;
            }
        }

        DetPotongan dpt = new DetPotongan();
        dpt.setIdGji(Integer.parseInt(txIdGji.getText()));
        dpt.setIdPot(Integer.parseInt(txIdPot.getText()));
        dpt.setNmPot(txNmPot.getText());
        dpt.setJmlPot(jpot);

        SqlDetPotongan qdp = new SqlDetPotongan(KonekDB.getKonek());
        if(isEdpt){
            dpt.setIdDet(Integer.parseInt(txIdDP.getText()));
            qdp.update(dpt, dpt.getIdDet());
        }else{            
            qdp.insert(dpt);            
        }        
        
        tblPot.setModel(new TblDetPotongan(qdp.getAll(dpt.getIdGji())));
        AutoFitTableColumns.autoResizeTable(tblPot, true);
        
       /*
        tpot = tpot+dpt.getJmlPot();
        txTtPot.setText(df.format(tpot));

        gjb = gjk-tpot;
        lblBsGji.setText(df.format(gjb));
        */
        
        txNmPot.setText("");
        txJmPot.setText("");
        txTtPot.setText("0");
    }//GEN-LAST:event_btSpPotActionPerformed

    private void btEdPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdPotActionPerformed
        // TODO add your handling code here:
        btSpPot.setEnabled(true);
        btDlPot.setEnabled(false);
        txJmPot.setEnabled(true);
        btEdPot.setEnabled(false);
        isEdpt = true;
    }//GEN-LAST:event_btEdPotActionPerformed

    private void btDlPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDlPotActionPerformed
        // TODO add your handling code here:
        if (tblPot.getSelectedRow() >= 0 && JOptionPane.showConfirmDialog(this, "Data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == 0){
            SqlDetPotongan qdp = new SqlDetPotongan(KonekDB.getKonek());
            qdp.delete(Integer.parseInt(txIdDP.getText()));

            DetPotongan dpt = new DetPotongan();
            tblPot.setModel(new TblDetPotongan(qdp.getAll(Integer.parseInt(txIdGji.getText()))));
            AutoFitTableColumns.autoResizeTable(tblPot, true);
            txNmPot.setText("");
            txJmPot.setText("");
        }
    }//GEN-LAST:event_btDlPotActionPerformed

    private void tblPotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPotMouseClicked
        // TODO add your handling code here:
        txIdDP.setText(tblPot.getValueAt(tblPot.getSelectedRow(),0).toString());
        txNmPot.setText(tblPot.getValueAt(tblPot.getSelectedRow(),1).toString());
        txJmPot.setText(tblPot.getValueAt(tblPot.getSelectedRow(),2).toString());

        /******************************************************************/
        String sql = "SELECT * FROM tbl_detpotgaj WHERE idDpj='"+txIdDP.getText()+"'";
        try {
            Connection conn = KonekDB.getKonek();
            Statement sm = conn.createStatement();
            ResultSet rs = sm.executeQuery(sql);
            if(rs.next()){
                txIdPot.setText(Integer.toString(rs.getInt("idPotong")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
        }
        /******************************************************************/

       // txIdPot.setText(tblInp.getValueAt(tblInp.getSelectedRow(),0).toString());

        btEdPot.setEnabled(true);
        btDlPot.setEnabled(true);
        btSpPot.setEnabled(false);
        txJmPot.setEnabled(false);
    }//GEN-LAST:event_tblPotMouseClicked

    private void btKtGjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKtGjiActionPerformed
        // TODO add your handling code here:
        double ins,bns;
        if(txNmPeg.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Absensi Pegawai harus dipilih!", "Peringatan", JOptionPane.OK_OPTION);
            btCrAbs.requestFocus();
            return;        
        }
        if(txInstf.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insentif harus diisi.!, minimal 0","Peringatan",JOptionPane.OK_OPTION);
            txInstf.requestFocus();
            return;
        }else {
            try {
                ins = Double.parseDouble(txInstf.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Insentif harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                txInstf.requestFocus();
                return;
            }
        }
        if(txBns.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Bonus harus diisi.!, minimal 0","Peringatan",JOptionPane.OK_OPTION);
            txBns.requestFocus();
            return;
        } else {
            try {
                bns = Double.parseDouble(txBns.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Bonus harus diisi Angka!","Peringatan",JOptionPane.OK_OPTION);
                txBns.requestFocus();
                return;
            }
        }
        
        gj = Double.parseDouble(txAwGji.getText());      
        gjk = gj+ins+bns;
        txKtGji.setText(df.format(gjk));
    }//GEN-LAST:event_btKtGjiActionPerformed

    private void btTtPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTtPotActionPerformed
        // TODO add your handling code here:
        
        if(txKtGji.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "Klik '+' pada Gaji Kotor terlebih dahulu!", "Peringatan", JOptionPane.OK_OPTION);
            btKtGji.requestFocus();
            return;
        }
        /******************************************************************/
        /*cari dulu apakah data utk idGaji trsbt ada*/
        String sqla = "SELECT * FROM tbl_detpotgaj WHERE idGaji='"+txIdGji.getText()+"'";
        /*klo data utk idGaji trsbt ada, baru jumlahnya di totalkan*/
        String sql = "SELECT SUM(jmlPotong) AS ttl FROM tbl_detpotgaj WHERE idGaji='"+txIdGji.getText()+"'";
        Connection conn = KonekDB.getKonek();
        try {            
            Statement sm = conn.createStatement();
            ResultSet rsa = sm.executeQuery(sqla);
            if(rsa.next()){
                System.out.println(rsa.next());
                ResultSet rs = sm.executeQuery(sql);
                if(rs.next()){
                    txTtPot.setText(df.format(rs.getInt("ttl")));
                }
                                    
            } else {
                JOptionPane.showMessageDialog(this,"Potongan harus diisi.!, minimal 1 Potongan","Peringatan",JOptionPane.OK_OPTION);
                btCrPot.requestFocus();
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
        }
        /******************************************************************/
       // tpot = tpot+dpt.getJmlPot();
       // txTtPot.setText(df.format(tpot));

        gjk = Double.parseDouble(txKtGji.getText());
        gjb = gjk-Double.parseDouble(txTtPot.getText());
        lblBsGji.setText(df.format(gjb));
    }//GEN-LAST:event_btTtPotActionPerformed

    private void txCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txCariMouseClicked
        // TODO add your handling code here:
        txCari.setText("");
        txCari.requestFocus();
        txCari.setForeground(Color.BLACK);
    }//GEN-LAST:event_txCariMouseClicked

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        // TODO add your handling code here:
        if(txCari.getText().equals("Masukkan NO. SLIP disini.") || txCari.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Masukkan Slip Gaji yang dicari!", "Peringatan", JOptionPane.OK_OPTION);
            txCari.setText("");
            txCari.requestFocus();
            return;
        }
        
        String sl = txCari.getText();
        String sql = "SELECT * FROM tbl_penggajian WHERE noSlip LIKE '%"+sl+"%'";
        Connection conn = KonekDB.getKonek();
        try {
            Statement sm = conn.createStatement();
            ResultSet rs = sm.executeQuery(sql);
            if(rs.next()){
                //txIdAbs.setText(Integer.toString(rs.getInt("idAbsen")));
                SqlPenggajian qgj = new SqlPenggajian(KonekDB.getKonek());        
                tblGaji.setModel(new TblPenggajian(qgj.getAll(txCari.getText())));
                AutoFitTableColumns.autoResizeTable(tblGaji, true);
            }else{
                JOptionPane.showMessageDialog(this, "Slip yang dicari tidak ditemukan!", "Peringatan", JOptionPane.OK_OPTION);
                txCari.setText("");
                txCari.requestFocus();
                tampilData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPenggajian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCariActionPerformed
/*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPenggajian().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JButton btCrAbs;
    private javax.swing.JButton btCrPot;
    private javax.swing.JButton btDlPot;
    private javax.swing.JButton btEdPot;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btKtGji;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btSpPot;
    private javax.swing.JButton btTtPot;
    private javax.swing.JButton btTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBsGji;
    private javax.swing.JLabel lblUsr;
    private tools.MyPaanelInt myPaanelInt1;
    private javax.swing.JPanel pnlId;
    private javax.swing.JPanel pnlInp;
    private javax.swing.JTable tblGaji;
    private javax.swing.JTable tblInp;
    private javax.swing.JTable tblPot;
    private javax.swing.JTextField txAwGji;
    private javax.swing.JTextField txBln;
    private javax.swing.JTextField txBns;
    private javax.swing.JTextField txCari;
    private javax.swing.JTextField txGaPok;
    private javax.swing.JTextField txHrHdr;
    private javax.swing.JTextField txHrKrj;
    private javax.swing.JTextField txIdAbs;
    private javax.swing.JTextField txIdDP;
    private javax.swing.JTextField txIdGji;
    private javax.swing.JTextField txIdPot;
    private javax.swing.JTextField txIdUsr;
    private javax.swing.JTextField txInstf;
    private javax.swing.JTextField txJmPot;
    private javax.swing.JTextField txKtGji;
    private javax.swing.JTextField txNmJab;
    private javax.swing.JTextField txNmPeg;
    private javax.swing.JTextField txNmPot;
    private javax.swing.JTextField txSlip;
    private javax.swing.JTextField txThn;
    private javax.swing.JTextField txTtPot;
    // End of variables declaration//GEN-END:variables

    private void statusAwal(){
        kosongJText();
        setInputan(false);
        btSimpan.setText("Tambah");
        btEdit.setText("Edit");
        btHapus.setText("Hapus");
        btTutup.setText("Tutup");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
        pnlId.setVisible(false);
       // pnlInp.setVisible(false);
    }

    private void siapSimpan(){
        setInputan(true);
        btSimpan.setText("Simpan");
        btTutup.setText("Batal");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
    }

    private void tabelKlik(){
        setInputan(false);
        btSimpan.setEnabled(false);
        btEdit.setEnabled(true);
        btHapus.setEnabled(true);
        btTutup.setText("Batal");
    }

    private void kosongJText(){
        txIdGji.setText("");
        txSlip.setText("");
        txIdAbs.setText("");
        txNmPeg.setText("");
        txNmJab.setText("");
        txGaPok.setText("0");
        txBln.setText("");
        txThn.setText("");
        txHrKrj.setText("");
        txHrHdr.setText("");
        txAwGji.setText("0");
        txInstf.setText("0");
        txBns.setText("0");
        txKtGji.setText("0");
        txIdDP.setText("");
        txIdPot.setText("");
        txNmPot.setText("");
        txJmPot.setText("");
        txTtPot.setText("0");
        lblBsGji.setText("0");
    }

    private void setInputan(boolean aktif){
        txSlip.setEnabled(false);
        txNmPeg.setEnabled(false);
        txNmJab.setEnabled(false);
        txGaPok.setEnabled(false);
        txBln.setEnabled(false);
        txThn.setEnabled(false);
        txHrKrj.setEnabled(false);
        txHrHdr.setEnabled(false);
        txAwGji.setEnabled(false);
        txInstf.setEnabled(aktif);
        txBns.setEnabled(aktif);
        txKtGji.setEnabled(false);
        txNmPot.setEnabled(false);
        txJmPot.setEnabled(aktif);
        txTtPot.setEnabled(false);
        btCrAbs.setEnabled(aktif);
        btKtGji.setEnabled(aktif);
        btCrPot.setEnabled(aktif);
        btSpPot.setEnabled(aktif);
        btEdPot.setEnabled(false);
        btDlPot.setEnabled(false);
        btTtPot.setEnabled(aktif);
        tblInp.setVisible(false);
        tblPot.setVisible(aktif);
        tblPot.setEnabled(aktif);
    }

    private void tampilData(){
        SqlPenggajian qgj = new SqlPenggajian(KonekDB.getKonek());
        tblGaji.setModel(new TblPenggajian(qgj.getAll()));
        AutoFitTableColumns.autoResizeTable(tblGaji, true);
    }

    private void tampilDataDetPot(){
        SqlDetPotongan qdp = new SqlDetPotongan(KonekDB.getKonek());
        tblPot.setModel(new TblDetPotongan(qdp.getAll(Integer.parseInt(txIdGji.getText()))));
        AutoFitTableColumns.autoResizeTable(tblPot, true);
    }

}
