/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmUtama.java
 *
 * Created on 05 Des 12, 15:48:42
 */

package form.gaji;

import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import tools.Waktu;

/**
 *
 * @author Prie
 */
public class frmUtama extends javax.swing.JFrame {

    private int idm;
    /** Creates new form frmUtama */
    public frmUtama() {
        initComponents();
        stAwl();
        initDateTime();
        setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logo.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanelImg1 = new tools.MyPanelImg();
        jPanel1 = new javax.swing.JPanel();
        ctrLogin = new usu.widget.glass.ButtonImageReflection();
        ctrKeluar = new usu.widget.glass.ButtonImageReflection();
        ctrPotongan = new usu.widget.glass.ButtonImageReflection();
        ctrJabatan = new usu.widget.glass.ButtonImageReflection();
        ctrPegawai = new usu.widget.glass.ButtonImageReflection();
        ctrPenggajian = new usu.widget.glass.ButtonImageReflection();
        ctrAbsensi = new usu.widget.glass.ButtonImageReflection();
        ctrLaporan = new usu.widget.glass.ButtonImageReflection();
        jPanel2 = new javax.swing.JPanel();
        lblTgl = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAdm = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnKelola = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        mnPrs = new javax.swing.JMenu();
        mnAbsensi = new javax.swing.JMenuItem();
        mnGaji = new javax.swing.JMenuItem();
        mnDta = new javax.swing.JMenu();
        mnPegawai = new javax.swing.JMenuItem();
        mnJabatan = new javax.swing.JMenuItem();
        mnPotong = new javax.swing.JMenuItem();
        mnLap = new javax.swing.JMenu();
        mnLaporan = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnBantuan = new javax.swing.JMenuItem();
        mnTentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penggajian Karyawan v1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "  Kontrol Data  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel1.setOpaque(false);

        ctrLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrLogin.png"))); // NOI18N
        ctrLogin.setText("LogIn");
        ctrLogin.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrLoginActionPerformed(evt);
            }
        });

        ctrKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit_1.png"))); // NOI18N
        ctrKeluar.setText("Keluar");
        ctrKeluar.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrKeluarActionPerformed(evt);
            }
        });

        ctrPotongan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrPotong.png"))); // NOI18N
        ctrPotongan.setText("Potongan");
        ctrPotongan.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrPotongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrPotonganActionPerformed(evt);
            }
        });

        ctrJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrJabatan.png"))); // NOI18N
        ctrJabatan.setText("Jabatan");
        ctrJabatan.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrJabatanActionPerformed(evt);
            }
        });

        ctrPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrPegawai.png"))); // NOI18N
        ctrPegawai.setText("Karyawan");
        ctrPegawai.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrPegawaiActionPerformed(evt);
            }
        });

        ctrPenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrlGaji.png"))); // NOI18N
        ctrPenggajian.setText("Penggajian");
        ctrPenggajian.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrPenggajianActionPerformed(evt);
            }
        });

        ctrAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrAbsensi.png"))); // NOI18N
        ctrAbsensi.setText("Absensi");
        ctrAbsensi.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrAbsensiActionPerformed(evt);
            }
        });

        ctrLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ctrLaporan.png"))); // NOI18N
        ctrLaporan.setText("Laporan");
        ctrLaporan.setFont(new java.awt.Font("Times New Roman", 1, 14));
        ctrLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctrLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ctrAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrPotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctrLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctrLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrPotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctrLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        lblTgl.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        lblTgl.setForeground(new java.awt.Color(255, 255, 0));
        lblTgl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tgl.png"))); // NOI18N
        lblTgl.setText("Tanggal");

        lblJam.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        lblJam.setForeground(new java.awt.Color(255, 255, 0));
        lblJam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jam.png"))); // NOI18N
        lblJam.setText("Waktu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(lblTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJam, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJam)
                    .addComponent(lblTgl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout myPanelImg1Layout = new javax.swing.GroupLayout(myPanelImg1);
        myPanelImg1.setLayout(myPanelImg1Layout);
        myPanelImg1Layout.setHorizontalGroup(
            myPanelImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelImg1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanelImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        myPanelImg1Layout.setVerticalGroup(
            myPanelImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelImg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mnAdm.setText("Admin");

        mnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnLogin.png"))); // NOI18N
        mnLogin.setText("Login");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        mnAdm.add(mnLogin);

        mnKelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnAdmin.png"))); // NOI18N
        mnKelola.setText("Kelola Data");
        mnKelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKelolaActionPerformed(evt);
            }
        });
        mnAdm.add(mnKelola);

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnAdm.add(mnKeluar);

        jMenuBar1.add(mnAdm);

        mnPrs.setText("Proses");

        mnAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnuAbsensi.png"))); // NOI18N
        mnAbsensi.setText("Absebsi");
        mnAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbsensiActionPerformed(evt);
            }
        });
        mnPrs.add(mnAbsensi);

        mnGaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnGaji.png"))); // NOI18N
        mnGaji.setText("Penggajian");
        mnGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGajiActionPerformed(evt);
            }
        });
        mnPrs.add(mnGaji);

        jMenuBar1.add(mnPrs);

        mnDta.setText("Data");

        mnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnPegawai.png"))); // NOI18N
        mnPegawai.setText("Data Pegawai");
        mnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPegawaiActionPerformed(evt);
            }
        });
        mnDta.add(mnPegawai);

        mnJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnJabatan.png"))); // NOI18N
        mnJabatan.setText("Data Jabatan");
        mnJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJabatanActionPerformed(evt);
            }
        });
        mnDta.add(mnJabatan);

        mnPotong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnPotong.png"))); // NOI18N
        mnPotong.setText("Data Potongan");
        mnPotong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPotongActionPerformed(evt);
            }
        });
        mnDta.add(mnPotong);

        jMenuBar1.add(mnDta);

        mnLap.setText("Laporan");

        mnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mnLaporan.png"))); // NOI18N
        mnLaporan.setText("Pilih Cetak Laporan");
        mnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanActionPerformed(evt);
            }
        });
        mnLap.add(mnLaporan);

        jMenuBar1.add(mnLap);

        jMenu5.setText("Info");

        mnBantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        mnBantuan.setText("Bantuan");
        jMenu5.add(mnBantuan);

        mnTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        mnTentang.setText("Tentang");
        mnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTentangActionPerformed(evt);
            }
        });
        jMenu5.add(mnTentang);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanelImg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanelImg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        // TODO add your handling code here:
        if(mnLogin.getText().equals("LogIn")){
            frmLogin lg = new frmLogin(this);
            lg.setVisible(true);
        }else{
            int jwb = JOptionPane.showConfirmDialog(null, "Anda yakin akan LogOut?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jwb == JOptionPane.YES_OPTION) {
                stAwl();
            }
        }
    }//GEN-LAST:event_mnLoginActionPerformed

    private void ctrLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrLoginActionPerformed
        // TODO add your handling code here:
        mnLoginActionPerformed(evt);
    }//GEN-LAST:event_ctrLoginActionPerformed

    private void ctrPotonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrPotonganActionPerformed
        // TODO add your handling code here:
        mnPotongActionPerformed(evt);
    }//GEN-LAST:event_ctrPotonganActionPerformed

    private void mnPotongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPotongActionPerformed
        // TODO add your handling code here:
        frmPotongan ptg = new frmPotongan();
        ptg.setVisible(true);
    }//GEN-LAST:event_mnPotongActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
        ijinOut();
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void ctrKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrKeluarActionPerformed
        // TODO add your handling code here:
        mnKeluarActionPerformed(evt);
    }//GEN-LAST:event_ctrKeluarActionPerformed

    private void mnJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJabatanActionPerformed
        // TODO add your handling code here:
        frmJabatan fjb = new frmJabatan();
        fjb.setVisible(true);
    }//GEN-LAST:event_mnJabatanActionPerformed

    private void ctrJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrJabatanActionPerformed
        // TODO add your handling code here:
        mnJabatanActionPerformed(evt);
    }//GEN-LAST:event_ctrJabatanActionPerformed

    private void mnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPegawaiActionPerformed
        // TODO add your handling code here:
        frmPegawai fgw = new frmPegawai();
        fgw.setVisible(true);
    }//GEN-LAST:event_mnPegawaiActionPerformed

    private void ctrPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrPegawaiActionPerformed
        // TODO add your handling code here:
        mnPegawaiActionPerformed(evt);
    }//GEN-LAST:event_ctrPegawaiActionPerformed

    private void mnKelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKelolaActionPerformed
        // TODO add your handling code here:
        frmUser usr = new frmUser();
        usr.setVisible(true);
    }//GEN-LAST:event_mnKelolaActionPerformed

    private void mnAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbsensiActionPerformed
        // TODO add your handling code here:
        frmAbsensi abs = new frmAbsensi();
        abs.setVisible(true);
    }//GEN-LAST:event_mnAbsensiActionPerformed

    private void ctrAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrAbsensiActionPerformed
        // TODO add your handling code here:
        mnAbsensiActionPerformed(evt);
    }//GEN-LAST:event_ctrAbsensiActionPerformed

    private void mnGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGajiActionPerformed
        // TODO add your handling code here:
        frmPenggajian gji = new frmPenggajian(this.getIdm());
        gji.setVisible(true);

    }//GEN-LAST:event_mnGajiActionPerformed

    private void ctrPenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrPenggajianActionPerformed
        // TODO add your handling code here:
        mnGajiActionPerformed(evt);
    }//GEN-LAST:event_ctrPenggajianActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ijinOut();
    }//GEN-LAST:event_formWindowClosing

    private void mnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanActionPerformed
        // TODO add your handling code here:
        frmLaporan flp = new frmLaporan();
        flp.setVisible(true);
    }//GEN-LAST:event_mnLaporanActionPerformed

    private void ctrLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrLaporanActionPerformed
        // TODO add your handling code here:
        mnLaporanActionPerformed(evt);
    }//GEN-LAST:event_ctrLaporanActionPerformed

    private void mnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTentangActionPerformed
        // TODO add your handling code here:
        frmTentang ftg = new frmTentang();
        ftg.setVisible(true);
    }//GEN-LAST:event_mnTentangActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    private void initDateTime(){
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        Date dt = new Date();
        lblTgl.setText(sdf.format(dt));
        Waktu jam = new Waktu(lblJam, 1);
    }

    private void ijinOut(){
        if(mnLogin.getText().equals("LogOut")){
            JOptionPane.showMessageDialog(this, "Harap LogOut terlebih dahulu!","Peringatan",JOptionPane.OK_OPTION);
            ctrLogin.requestFocus();
        }else{
            int jawab = JOptionPane.showConfirmDialog(null, "Anda yakin akan Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab==JOptionPane.YES_OPTION){
                System.exit(0);
            }            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.ButtonImageReflection ctrAbsensi;
    private usu.widget.glass.ButtonImageReflection ctrJabatan;
    private usu.widget.glass.ButtonImageReflection ctrKeluar;
    private usu.widget.glass.ButtonImageReflection ctrLaporan;
    private usu.widget.glass.ButtonImageReflection ctrLogin;
    private usu.widget.glass.ButtonImageReflection ctrPegawai;
    private usu.widget.glass.ButtonImageReflection ctrPenggajian;
    private usu.widget.glass.ButtonImageReflection ctrPotongan;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JMenuItem mnAbsensi;
    private javax.swing.JMenu mnAdm;
    private javax.swing.JMenuItem mnBantuan;
    private javax.swing.JMenu mnDta;
    private javax.swing.JMenuItem mnGaji;
    private javax.swing.JMenuItem mnJabatan;
    private javax.swing.JMenuItem mnKelola;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenu mnLap;
    private javax.swing.JMenuItem mnLaporan;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenuItem mnPegawai;
    private javax.swing.JMenuItem mnPotong;
    private javax.swing.JMenu mnPrs;
    private javax.swing.JMenuItem mnTentang;
    private tools.MyPanelImg myPanelImg1;
    // End of variables declaration//GEN-END:variables

    private void stAwl(){
        mnSet(false);
        mnLogin.setText("LogIn");
        ctrLogin.setText("LogIn");
    }
    
    public void siap(){
        mnSet(true);
        mnLogin.setText("LogOut");
        ctrLogin.setText("LogOut");
    }

    public void mnSet(boolean act){
        mnKelola.setEnabled(act);
        mnPrs.setEnabled(act);
        mnDta.setEnabled(act);
        mnLap.setEnabled(act);
        ctrAbsensi.setEnabled(act);
        ctrPenggajian.setEnabled(act);
        ctrPegawai.setEnabled(act);
        ctrJabatan.setEnabled(act);
        ctrPotongan.setEnabled(act);
        ctrLaporan.setEnabled(act);
    }

    public int getIdm() {
        return idm;
    }

    public void setIdm(int idm) {
        this.idm = idm;        
    }

    static {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
