/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmUser.java
 *
 * Created on 10 Des 12, 12:54:34
 */

package form.gaji;

import entity.User;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sql.methodes.SqlPegawai;
import sql.methodes.SqlUser;
import table.TblUser;
import tablechoice.TblChPegawai;
import tools.AutoFitTableColumns;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class frmUser extends Form {

    private boolean isEdit = false;
    /** Creates new form frmUser */
    public frmUser() {
        initComponents();
        statusAwal();
        tampilData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPaanelInt1 = new tools.MyPaanelInt();
        jPanel1 = new javax.swing.JPanel();
        lbIdAdmn = new javax.swing.JLabel();
        txIdAdmn = new javax.swing.JTextField();
        lbIdPeg = new javax.swing.JLabel();
        txIdPeg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txUsern = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pswAdm = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txNmAdm = new javax.swing.JTextField();
        btCrNm = new javax.swing.JButton();
        pnlNmAd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNmAdm = new javax.swing.JTable();
        btSimpan = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMAdmin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_RIGHT);
        setAnimationShow(usu.widget.constan.Animation.SHOW_FROM_LEFT);
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Data Admin ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        lbIdAdmn.setText("ID Admin");

        lbIdPeg.setText("ID Pegawai");

        jLabel4.setText("Username");

        txUsern.setText("jTextField4");

        jLabel5.setText("Password");

        pswAdm.setText("jPasswordField1");

        jLabel3.setText("Nama Admin");

        btCrNm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.png"))); // NOI18N
        btCrNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrNmActionPerformed(evt);
            }
        });

        pnlNmAd.setOpaque(false);

        tblNmAdm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblNmAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNmAdmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNmAdm);

        javax.swing.GroupLayout pnlNmAdLayout = new javax.swing.GroupLayout(pnlNmAd);
        pnlNmAd.setLayout(pnlNmAdLayout);
        pnlNmAdLayout.setHorizontalGroup(
            pnlNmAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        pnlNmAdLayout.setVerticalGroup(
            pnlNmAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNmAdLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(lbIdPeg)
                    .addComponent(lbIdAdmn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNmAd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txIdAdmn, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txIdPeg, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(pswAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txNmAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCrNm))
                    .addComponent(txUsern, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdAdmn)
                    .addComponent(txIdAdmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdPeg)
                    .addComponent(txIdPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txUsern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pswAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txNmAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCrNm))
                .addGap(18, 18, 18)
                .addComponent(pnlNmAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okeLgn.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_edit.png"))); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelLgn.png"))); // NOI18N
        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btTutup.setText("Tutup");
        btTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTutupActionPerformed(evt);
            }
        });

        tblMAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblMAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMAdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMAdmin);

        javax.swing.GroupLayout myPaanelInt1Layout = new javax.swing.GroupLayout(myPaanelInt1);
        myPaanelInt1.setLayout(myPaanelInt1Layout);
        myPaanelInt1Layout.setHorizontalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, myPaanelInt1Layout.createSequentialGroup()
                        .addComponent(btSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btTutup)))
                .addContainerGap())
        );
        myPaanelInt1Layout.setVerticalGroup(
            myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPaanelInt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPaanelInt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btEdit)
                    .addComponent(btHapus)
                    .addComponent(btTutup))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(myPaanelInt1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-393)/2, (screenSize.height-390)/2, 393, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equalsIgnoreCase("Tambah")){
            siapSimpan();
            kosongJText();
            btCrNm.requestFocus();
            isEdit = false;
        }else{
            if(txUsern.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Username harus diisi!", "Peringatan", JOptionPane.OK_OPTION);
                txUsern.requestFocus();
            }else if(pswAdm.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Password harus diisi.!", "Peringatan", JOptionPane.OK_OPTION);
                pswAdm.requestFocus();
            }else if(txIdPeg.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nama Admin harus dipilih!", "Peringatan", JOptionPane.OK_OPTION);
                btCrNm.requestFocus();
            }
            
            User usr = new User();
            usr.setIdPeg(Integer.parseInt(txIdPeg.getText()));
            usr.setUsrNme(txUsern.getText());
            usr.setPssWrd(pswAdm.getText());
            
            SqlUser qus = new SqlUser(KonekDB.getKonek());
            if(isEdit){
                usr.setIdAdm(Integer.parseInt(txIdAdmn.getText()));
                qus.update(usr, Integer.parseInt(txIdAdmn.getText()));
            }else{
                qus.insert(usr);
            }

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
            tampilData();
            statusAwal();
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        isEdit = true;
        siapSimpan();
        btCrNm.setEnabled(false);
    }//GEN-LAST:event_btEditActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        if (tblMAdmin.getSelectedRow() >= 0 && JOptionPane.showConfirmDialog(this, "Data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == 0){
            SqlUser qus = new SqlUser(KonekDB.getKonek());
            qus.delete(Integer.parseInt(txIdAdmn.getText()));

            tampilData();
            JOptionPane.showMessageDialog(this, "Data telah dihapus.");
            statusAwal();
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
        // TODO add your handling code here:
         if(evt.getActionCommand().equalsIgnoreCase("Tutup")){
            this.setVisible(false);
        }else{
            statusAwal();
        }
    }//GEN-LAST:event_btTutupActionPerformed

    private void tblMAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMAdminMouseClicked
        // TODO add your handling code here:
         tabelKlik();
        int idAdm =Integer.parseInt(tblMAdmin.getValueAt(tblMAdmin.getSelectedRow(),0).toString()) ;
        txIdAdmn.setText(tblMAdmin.getValueAt(tblMAdmin.getSelectedRow(),0).toString());
       // txIdPeg.setText(tblMAdmin.getValueAt(tblMAdmin.getSelectedRow(),1).toString());
        txNmAdm.setText(tblMAdmin.getValueAt(tblMAdmin.getSelectedRow(),1).toString());
        txUsern.setText(tblMAdmin.getValueAt(tblMAdmin.getSelectedRow(),2).toString());
        //pswAdm.setText(tblMAdmin.getValueAt(tblMAdmin.getSelectedRow(),5).toString());
        
        /*-------------------------------------------------------------------*/
        String sql = "SELECT * FROM tbl_user WHERE idUser='"+idAdm+"'";        
        try {
            Connection conn = KonekDB.getKonek();
            Statement sm = conn.createStatement();
            ResultSet rs = sm.executeQuery(sql);
            if(rs.next()){
                txIdPeg.setText(Integer.toString(rs.getInt("idPegawai")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMAdminMouseClicked

    private void btCrNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrNmActionPerformed
        // TODO add your handling code here:
        pnlNmAd.setVisible(true);
        SqlPegawai qpg = new SqlPegawai(KonekDB.getKonek());
        tblNmAdm.setModel(new TblChPegawai(qpg.getAll()));
        AutoFitTableColumns.autoResizeTable(tblNmAdm, true);
    }//GEN-LAST:event_btCrNmActionPerformed

    private void tblNmAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNmAdmMouseClicked
        // TODO add your handling code here:
        txIdPeg.setText(tblNmAdm.getValueAt(tblNmAdm.getSelectedRow(),0).toString());
        txNmAdm.setText(tblNmAdm.getValueAt(tblNmAdm.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tblNmAdmMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrNm;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTutup;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbIdAdmn;
    private javax.swing.JLabel lbIdPeg;
    private tools.MyPaanelInt myPaanelInt1;
    private javax.swing.JPanel pnlNmAd;
    private javax.swing.JPasswordField pswAdm;
    private javax.swing.JTable tblMAdmin;
    private javax.swing.JTable tblNmAdm;
    private javax.swing.JTextField txIdAdmn;
    private javax.swing.JTextField txIdPeg;
    private javax.swing.JTextField txNmAdm;
    private javax.swing.JTextField txUsern;
    // End of variables declaration//GEN-END:variables

    private void statusAwal(){
        kosongJText();
        setInputan(false);
        btSimpan.setText("Tambah");
        btEdit.setText("Edit");
        btHapus.setText("Hapus");
        btTutup.setText("Tutup");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
        pnlNmAd.setVisible(false);
        lbIdAdmn.setVisible(false);
        txIdAdmn.setVisible(false);
        lbIdPeg.setVisible(false);
        txIdPeg.setVisible(false);
    }

    private void siapSimpan(){
        setInputan(true);
        btSimpan.setText("Simpan");
        btTutup.setText("Batal");
        btSimpan.setEnabled(true);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
    }

    private void tabelKlik(){
        setInputan(false);
        btSimpan.setEnabled(false);
        btEdit.setEnabled(true);
        btHapus.setEnabled(true);
        btTutup.setText("Batal");
    }

    private void kosongJText(){
        txIdPeg.setText("");
        txIdAdmn.setText("");
        txNmAdm.setText("");
        txUsern.setText("");
        pswAdm.setText("");
    }

    private void setInputan(boolean aktif){
        txNmAdm.setEnabled(false);
        txUsern.setEnabled(aktif);
        pswAdm.setEnabled(aktif);
        btCrNm.setEnabled(aktif);
    }
    
    private void tampilData(){
        SqlUser qus = new SqlUser(KonekDB.getKonek());
        tblMAdmin.setModel(new TblUser(qus.getAll()));
        AutoFitTableColumns.autoResizeTable(tblMAdmin, true);
    }
}
