/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reportRekapAll.java
 *
 * Created on 18 Des 12, 10:55:44
 */

package form.report;

import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class reportRekapAll extends Form {

    /** Creates new form reportRekapAll
     * @param bln
     * @param thn */
    public reportRekapAll(String bln, int thn) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        cetak(bln, thn);
    }

    private void cetak(String bln, int thn){
        String nmFile = "src/report/RekapGaji.jasper";
        HashMap param = new HashMap();
        param.put("bulan", bln);
        param.put("tahun", thn);

        Connection conn = KonekDB.getKonek();
        try {
            JasperPrint ctk = JasperFillManager.fillReport(nmFile, param, conn);
            JRViewer vwr = new JRViewer(ctk);
            getContentPane().add(vwr);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak tersedia!","Cetak Data",JOptionPane.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Laporan Rekapitulasi Penggajian");
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_BOTTOM);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-489)/2, (screenSize.height-340)/2, 489, 340);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
