/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reportSlipAll.java
 *
 * Created on 19 Des 12, 5:32:39
 */

package form.report;

import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import tools.KonekDB;
import usu.widget.Form;

/**
 *
 * @author Prie
 */
public class reportSlipAll extends Form {

    /** Creates new form reportSlipAll
     * @param bln
     * @param thn
     * @param slp */
    public reportSlipAll(String bln, int thn, String slp) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        cetak(bln, thn, slp);
    }

    private void cetak(String bln, int thn, String slp){
        String nmFile;
        HashMap prm = new HashMap();
        if(slp.trim().equals("")){
            nmFile = "src/report/SlipGaji.jasper";
            prm.put("bulan", bln);
            prm.put("tahun", thn);
        }else{
            nmFile = "src/report/SlipGajiO.jasper";
            prm.put("slip", slp);
        }
        Connection conn = KonekDB.getKonek();
        try {
            JasperPrint ctk = JasperFillManager.fillReport(nmFile, prm, conn);
            JRViewer vwr = new JRViewer(ctk);
            getContentPane().add(vwr);
        } catch (JRException ex) {
            Logger.getLogger(reportSlipAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Laporan Slip Pegawai");
        setAnimationHide(usu.widget.constan.Animation.HIDE_TO_BOTTOM);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-334)/2, 408, 334);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
